# Generated by Django 4.1.3 on 2023-01-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="commandList",
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
