# Generated by Django 4.1.3 on 2023-01-12 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectName", models.CharField(max_length=200)),
                ("kProjectName", models.CharField(max_length=200)),
                ("dokerImageName", models.CharField(max_length=200)),
                ("gkeServiceName", models.CharField(max_length=200)),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
